
export const PRODUCTS = [
    // Electronics & Computers
    {
        name: 'Wireless Bluetooth Headphones',
        category: 'Electronics & Computers',
        description: 'High-quality over-ear headphones with noise-cancellation and long battery life.',
        imageURL: '/images/shoes',
        rating: 4.5,
        numberOfRatings: 320,
        price: 99.99,
    },
    {
        name: '4K Ultra HD Smart TV',
        category: 'Electronics & Computers',
        description: 'A stunning 55-inch TV with vibrant picture quality and smart features.',
        imageURL: '/images/shoes',
        rating: 4.7,
        numberOfRatings: 250,
        price: 599.99,
    },
    {
        name: 'Gaming Laptop',
        category: 'Electronics & Computers',
        description: 'Powerful laptop equipped with the latest graphics card and fast processor.',
        imageURL: '/images/shoes',
        rating: 4.8,
        numberOfRatings: 180,
        price: 1299.99,
    },
    {
        name: 'Wireless Mouse',
        category: 'Electronics & Computers',
        description: 'Ergonomic mouse with customizable buttons and smooth tracking.',
        imageURL: '/images/shoes',
        rating: 4.3,
        numberOfRatings: 510,
        price: 29.99,
    },
    {
        name: 'Mechanical Keyboard',
        category: 'Electronics & Computers',
        description: 'RGB backlit keyboard with tactile keys perfect for gaming and productivity.',
        imageURL: '/images/shoes',
        rating: 4.6,
        numberOfRatings: 400,
        price: 79.99,
    },
    {
        name: 'Portable SSD 1TB',
        category: 'Electronics & Computers',
        description: 'Compact and fast storage solution for data transfer and backups.',
        imageURL: '/images/shoes',
        rating: 4.9,
        numberOfRatings: 620,
        price: 149.99,
    },

    // Fashion & Accessories
    {
        name: 'Leather Jacket',
        category: 'Fashion & Accessories',
        description: 'Stylish and durable leather jacket for a sleek look.',
        imageURL: '/images/shoes',
        rating: 4.7,
        numberOfRatings: 150,
        price: 199.99,
    },
    {
        name: 'Sneakers',
        category: 'Fashion & Accessories',
        description: 'Comfortable and trendy sneakers for everyday wear.',
        imageURL: '/images/shoes',
        rating: 4.5,
        numberOfRatings: 230,
        price: 59.99,
    },
    {
        name: 'Wristwatch',
        category: 'Fashion & Accessories',
        description: 'Elegant wristwatch with a minimalist design and water resistance.',
        imageURL: '/images/shoes',
        rating: 4.4,
        numberOfRatings: 300,
        price: 89.99,
    },
    {
        name: 'Sunglasses',
        category: 'Fashion & Accessories',
        description: 'UV-protected, stylish sunglasses perfect for sunny days.',
        imageURL: '/images/shoes',
        rating: 4.2,
        numberOfRatings: 120,
        price: 24.99,
    },
    {
        name: 'Handbag',
        category: 'Fashion & Accessories',
        description: 'Spacious handbag with multiple compartments for daily use.',
        imageURL: '/images/shoes',
        rating: 4.6,
        numberOfRatings: 180,
        price: 49.99,
    },
    {
        name: 'Scarf Set',
        category: 'Fashion & Accessories',
        description: 'Set of cozy, colorful scarves made of premium materials.',
        imageURL: '/images/shoes',
        rating: 4.3,
        numberOfRatings: 75,
        price: 19.99,
    },

    // Home & Kitchen
    {
        name: 'Air Fryer',
        category: 'Home & Kitchen',
        description: 'Compact air fryer for healthy, oil-free cooking.',
        imageURL: '/images/shoes',
        rating: 4.8,
        numberOfRatings: 580,
        price: 89.99,
    },
    {
        name: 'Blender',
        category: 'Home & Kitchen',
        description: 'High-powered blender for smoothies, soups, and sauces.',
        imageURL: '/images/shoes',
        rating: 4.6,
        numberOfRatings: 310,
        price: 59.99,
    },
    {
        name: 'Cast Iron Skillet',
        category: 'Home & Kitchen',
        description: 'Heavy-duty skillet perfect for searing, baking, and frying.',
        imageURL: '/images/shoes',
        rating: 4.7,
        numberOfRatings: 220,
        price: 34.99,
    },
    {
        name: 'Coffee Maker',
        category: 'Home & Kitchen',
        description: 'Automatic coffee maker with programmable settings.',
        imageURL: '/images/shoes',
        rating: 4.5,
        numberOfRatings: 400,
        price: 49.99,
    },
    {
        name: 'Knife Set',
        category: 'Home & Kitchen',
        description: 'Professional knife set with ergonomic handles and sharp blades.',
        imageURL: '/images/shoes',
        rating: 4.8,
        numberOfRatings: 290,
        price: 99.99,
    },
    {
        name: 'Vacuum Cleaner',
        category: 'Home & Kitchen',
        description: 'Lightweight and powerful vacuum for efficient cleaning.',
        imageURL: '/images/shoes',
        rating: 4.4,
        numberOfRatings: 450,
        price: 129.99,
    },
    // Beauty & Personal Care
{
    name: 'Moisturizing Lotion',
    category: 'Beauty & Personal Care',
    description: 'Hydrating lotion for smooth and healthy skin.',
    imageURL: '/images/shoes',
    rating: 4.5,
    numberOfRatings: 150,
    price: 12.99,
},
{
    name: 'Hair Straightener',
    category: 'Beauty & Personal Care',
    description: 'Ceramic hair straightener for sleek and shiny hair.',
    imageURL: '/images/shoes',
    rating: 4.6,
    numberOfRatings: 230,
    price: 39.99,
},
{
    name: 'Essential Oil Set',
    category: 'Beauty & Personal Care',
    description: 'Collection of essential oils for relaxation and aromatherapy.',
    imageURL: '/images/shoes',
    rating: 4.8,
    numberOfRatings: 120,
    price: 24.99,
},
{
    name: 'Face Mask Pack',
    category: 'Beauty & Personal Care',
    description: 'Set of rejuvenating face masks for glowing skin.',
    imageURL: '/images/shoes',
    rating: 4.4,
    numberOfRatings: 180,
    price: 9.99,
},
{
    name: 'Makeup Brush Set',
    category: 'Beauty & Personal Care',
    description: 'Professional brush set for flawless makeup application.',
    imageURL: '/images/shoes',
    rating: 4.7,
    numberOfRatings: 90,
    price: 19.99,
},
{
    name: 'Electric Shaver',
    category: 'Beauty & Personal Care',
    description: 'Rechargeable electric shaver for a close and comfortable shave.',
    imageURL: '/images/shoes',
    rating: 4.3,
    numberOfRatings: 220,
    price: 49.99,
},

// Health & Wellness
{
    name: 'Yoga Mat',
    category: 'Health & Wellness',
    description: 'Non-slip yoga mat for comfortable and safe workouts.',
    imageURL: '/images/shoes',
    rating: 4.8,
    numberOfRatings: 300,
    price: 29.99,
},
{
    name: 'Dumbbell Set',
    category: 'Health & Wellness',
    description: 'Adjustable dumbbells for strength training at home.',
    imageURL: '/images/shoes',
    rating: 4.5,
    numberOfRatings: 180,
    price: 79.99,
},
{
    name: 'Resistance Bands',
    category: 'Health & Wellness',
    description: 'Set of resistance bands for versatile exercises.',
    imageURL: '/images/shoes',
    rating: 4.6,
    numberOfRatings: 220,
    price: 19.99,
},
{
    name: 'Vitamins & Supplements',
    category: 'Health & Wellness',
    description: 'Daily multivitamins to boost overall health.',
    imageURL: '/images/shoes',
    rating: 4.4,
    numberOfRatings: 500,
    price: 14.99,
},
{
    name: 'Foam Roller',
    category: 'Health & Wellness',
    description: 'High-density foam roller for muscle recovery and massage.',
    imageURL: '/images/shoes',
    rating: 4.7,
    numberOfRatings: 130,
    price: 24.99,
},
{
    name: 'Smart Scale',
    category: 'Health & Wellness',
    description: 'Digital scale with body composition tracking.',
    imageURL: '/images/shoes',
    rating: 4.5,
    numberOfRatings: 250,
    price: 39.99,
},

// Toys & Games
{
    name: 'Board Game',
    category: 'Toys & Games',
    description: 'Classic strategy board game for family fun.',
    imageURL: '/images/shoes',
    rating: 4.8,
    numberOfRatings: 620,
    price: 29.99,
},
{
    name: 'Building Blocks',
    category: 'Toys & Games',
    description: 'Creative building block set for kids and adults.',
    imageURL: '/images/shoes',
    rating: 4.7,
    numberOfRatings: 410,
    price: 24.99,
},
{
    name: 'Remote Control Car',
    category: 'Toys & Games',
    description: 'High-speed remote control car with durable build.',
    imageURL: '/images/shoes',
    rating: 4.5,
    numberOfRatings: 150,
    price: 34.99,
},
{
    name: 'Puzzle Set',
    category: 'Toys & Games',
    description: 'Challenging and fun puzzle set for all ages.',
    imageURL: '/images/shoes',
    rating: 4.6,
    numberOfRatings: 180,
    price: 19.99,
},
{
    name: 'Action Figures',
    category: 'Toys & Games',
    description: 'Set of popular action figures for imaginative play.',
    imageURL: '/images/shoes',
    rating: 4.4,
    numberOfRatings: 130,
    price: 14.99,
},
{
    name: 'Card Game',
    category: 'Toys & Games',
    description: 'Exciting card game for quick and strategic gameplay.',
    imageURL: '/images/shoes',
    rating: 4.3,
    numberOfRatings: 200,
    price: 9.99,
},

// Sports & Outdoors
{
    name: 'Camping Tent',
    category: 'Sports & Outdoors',
    description: 'Lightweight and easy-to-setup tent for camping trips.',
    imageURL: '/images/shoes',
    rating: 4.7,
    numberOfRatings: 400,
    price: 99.99,
},
{
    name: 'Hiking Backpack',
    category: 'Sports & Outdoors',
    description: 'Durable backpack with multiple compartments for outdoor adventures.',
    imageURL: '/images/shoes',
    rating: 4.6,
    numberOfRatings: 350,
    price: 59.99,
},
{
    name: 'Sleeping Bag',
    category: 'Sports & Outdoors',
    description: 'Warm and comfortable sleeping bag for outdoor use.',
    imageURL: '/images/shoes',
    rating: 4.8,
    numberOfRatings: 280,
    price: 49.99,
},
{
    name: 'Fishing Rod',
    category: 'Sports & Outdoors',
    description: 'Telescopic fishing rod with a lightweight design.',
    imageURL: '/images/shoes',
    rating: 4.5,
    numberOfRatings: 160,
    price: 39.99,
},
{
    name: 'Cycling Helmet',
    category: 'Sports & Outdoors',
    description: 'Safety helmet with an adjustable strap for cycling.',
    imageURL: '/images/shoes',
    rating: 4.9,
    numberOfRatings: 210,
    price: 29.99,
},
{
    name: 'Running Shoes',
    category: 'Sports & Outdoors',
    description: 'Comfortable running shoes with shock-absorbing soles.',
    imageURL: '/images/shoes',
    rating: 4.7,
    numberOfRatings: 300,
    price: 79.99,
},

// Books & Media
{
    name: 'Mystery Novel',
    category: 'Books & Media',
    description: 'A thrilling mystery novel with twists and turns.',
    imageURL: '/images/shoes',
    rating: 4.6,
    numberOfRatings: 320,
    price: 14.99,
},
{
    name: 'Science Fiction Book',
    category: 'Books & Media',
    description: 'A captivating sci-fi story that takes you to another world.',
    imageURL: '/images/shoes',
    rating: 4.5,
    numberOfRatings: 210,
    price: 12.99,
},
{
    name: 'Self-Help Guide',
    category: 'Books & Media',
    description: 'Inspirational self-help book to boost personal growth.',
    imageURL: '/images/shoes',
    rating: 4.8,
    numberOfRatings: 180,
    price: 19.99,
},
{
    name: 'Cookbook',
    category: 'Books & Media',
    description: 'Recipe book with easy-to-follow steps for delicious meals.',
    imageURL: '/images/shoes',
    rating: 4.7,
    numberOfRatings: 150,
    price: 24.99,
},
{
    name: 'Biography',
    category: 'Books & Media',
    description: 'A detailed biography of a renowned public figure.',
    imageURL: '/images/shoes',
    rating: 4.4,
    numberOfRatings: 95,
    price: 18.99,
},
{
    name: 'Educational Workbook',
    category: 'Books & Media',
    description: 'Workbook with exercises for learning and skill-building.',
    imageURL: '/images/shoes',
    rating: 4.5,
    numberOfRatings: 130,
    price: 9.99,
},
];

export interface Product {
    name: string;
    category : {
        name : string ;
        slug : string ; 
        _id: string ; 
    } ;
    "Sub-Category" : {
        name : string ;
        slug : string ;
        _id : string ; 
        parentCategory : string ;
    } ;
    description: string;
    price: number;
    rating?: number;
    numberOfRatings?: number;
    image: string;  // or `string[]` if it’s an array of URLs
  }